version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db_test'              # name of database
      MYSQL_USER: 'user_test'                # sample is the name of user
      MYSQL_PASSWORD: 'password_test'          # password for sample user
      MYSQL_ROOT_PASSWORD: 'password_test'     # password for root user
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8080:80"